Thesis-Rails/config/routes.rb
GeoquestEditor::Application.routes.draw do



  resources :multicachings

  resources :geocachings

  get "interconnections/show"

  get "profile/show"

  get "xmleditor/show"

  resources :users
  resource :session
  resource :profile, :only =>  [:show], :controller => :profile
  resources :projects do
    resources :missions
    resource :image_gallery,  :only => [:show], :controller => :image_gallery
    resource :audio_gallery,  :only => [:show], :controller => :audio_gallery
    resource :xmleditor, :only => [:show], :controller => :xmleditor
    resource :interconnections, :only => [:show], :controller => :interconnections
    match 'deploy' => "projects#deploy", :as => 'deploy', :controller => :projects
    match 'delete' => "projects#delete", :as => 'delete', :controller => :projects

    match 'image_gallery/uploadFile' => "image_gallery#uploadFile", :as => "image_gallery/uploadFile"
    match 'audio_gallery/uploadFile' => "audio_gallery#uploadFile", :as => "audio_gallery/uploadFile"
  end


  match '/commands/execute' => "commands#execute", :as => "commands/execute" #Rework as /ajax/execute ?
  match '/ajax/query' => "query#execute", :as => "ajax/query"
  match '/ajax/show_dir' => "query#show_dir", :as => "ajax/show_dir"
  match '/ajax/show_missions' => "query#show_missions", :as => "ajax/show_missions"
  match '/ajax/get_next_mission_id' => "query#get_next_mission_id", :as => "ajax/get_next_mission_id"
  match '/ajax/get_next_hotspot_id' => "query#get_next_hotspot_id", :as => "ajax/get_next_hotspot_id"
  match '/ajax/get_next_rule_id' => "query#get_next_rule_id", :as => "ajax/get_next_rule_id"
  match '/ajax/show_mission_interconnections' => "query#show_mission_interconnections", :as => "ajax/show_mission_interconnections"
  match '/ajax/show_images' => "query#show_images", :as => "ajax/show_images"
  match '/ajax/show_audio' => "query#show_audio", :as => "ajax/show_audio"
  match '/ajax/show_mission_types' => "query#show_mission_types", :as => "ajax/show_mission_types"
  match '/ajax/show_rule' => "query#show_rule", :as => "ajax/show_rule"
  match '/ajax/is_image_used' => "query#is_image_used", :as => "ajax/is_image_used"
  match '/ajax/is_audio_used' => "query#is_audio_used", :as => "ajax/is_audio_used"
  match '/ajax/show_rules_as_tree' => "query#show_rules_as_tree", :as => "ajax/show_rules_as_tree"
  match '/ajax/updateUserProperties' => "profile#update_user_properties", :as => "ajax/updateUserProperties"

  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
  match '/multicaching' => "multicachings#index", :as => "view"
  match '/geocaching/generate_xml_file' => "geocachings#generate_xml_file" , :as => :generate_xml_file
  match '/register' => "users#new", :as => "register"

  match '/repositories/repolist.php' => "repository#repolist"
  match '/repositories/:name' => "repository#show"
  match '/repositories/:name/gamelist.php' => "repository#gamelist"
  match '/repositories/:name/games/:file.zip' => "repository#download"

  root :to => "welcome#index"

end

Thesis-Rails/app/views/shared/_editor_control.html.erb
<%= javascript_include_tag 'shared/fold_in'  %>
<a href="/multicaching" class="Geocaching_button round">GeoCaching Mode</a>

<div id="control">



<h5> Editor Navigation</h5>

<%= link_to "Logout", logout_path, :class => 'editor_link'  %> <br />
<%= link_to "Create new Project", new_project_path, :class => 'editor_link' %> <br />
<%= link_to "Project overview", projects_path, :class => 'editor_link title-as-tooltip', :title => "Click here to list all your projects" %> <br />
<%= link_to "Profile", profile_path, :class => 'editor_link title-as-tooltip', :title => "Click here to edit your personal data, e.g. your email-address or your password." %> <br />
<br />
<br />

<h5> Projekt options </h5>

<% unless @project.nil? or @project.new_record? %>

<%= link_to "Project home", project_path(@project.id), :class => 'editor_link' %> <br />
<%= link_to "Mission interconnection", project_interconnections_path(@project.id), :class => 'editor_link title-as-tooltip', :title => 'Here you can edit the rules which connect the different missions and hotspots.' %> <br />
<%= link_to "Image Gallery", project_image_gallery_path(@project.id), :class => 'editor_link title-as-tooltip', :title => "Here you can upload new images or remove, rename or delete the existing ones." %> <br />
<%= link_to "Audio Gallery", project_audio_gallery_path(@project.id), :class => 'editor_link title-as-tooltip', :title => "Here you can upload new audio files or remove, rename or delete the existing ones." %> <br />
<%= link_to "Edit game.xml", project_xmleditor_path(@project.id), :class => 'editor_link title-as-tooltip', :title => "Here you can edit directly the game.xml. Only for advanced users." %> <br />
<%= link_to "Edit game.xml", project_xmleditor_path(@project.id), :class => 'editor_link title-as-tooltip', :title => "Here you can edit directly the game.xml. Only for advanced users." %> <br />

<% end %>

<h5> Extern </h5>

<a class="editor_link" href="/repositories/<%= @current_user.name %>">My Repository</a>

<br />
<br />

  <img id="rightFoldIn" src="/images/BlueArrowRight.gif" />
</div>

Thesis-Rails/app/views/shared/_header.html.erb
<div class="header">
<h1> 
  <%= link_to @project.name, project_path(@project.id), :id => 'caption' %>

</h1>
</div>

Thesis-Rails/app/views/shared/_image_selector.html.erb
<div class="hiddenDiv" id="imagePopupDiv">
  <div class="popup">
    <div class="popup-header">
      <h2>Select image</h2>
      <a href="javascript:;" onclick="$.closePopupLayer('imagePopup')" title="Close" class="close-link">Close</a>
      <br clear="all" />
    </div>

    <div class="popup-body">
    </div>
  </div>
</div>

Thesis-Rails/app/views/shared/_mission_navigation.html.erb
<%= javascript_include_tag 'jquery/jquery.jstree' %>
<%= javascript_include_tag 'shared/mission_list' %>
<%= javascript_include_tag 'shared/fold_in' %>

<%= javascript_include_tag "commands/command" %>
<%= javascript_include_tag "commands/missions" %>

<div id="navigation">
  <h5> Mission Navigation </h5>



  <% unless @project.nil? or @project.new_record? %>

  <div id="missionTree" class="title-as-tooltip" title="Click on a mission to edit it.<br />Use the contextmenu to delete, rename or add new missions.">
   </div>

  <% else %>

  No project selected

  <% end %>



  <img id="leftFoldIn" src="/images/BlueArrowLeft.gif" />
</div>